// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZDkE2t7YBDBh_0M4LRW3jQ-iW1uqvNps',
    appId: '1:1079119056326:android:40383c0611e0666bfef6c7',
    messagingSenderId: '1079119056326',
    projectId: 'movie-app-c4061',
    storageBucket: 'movie-app-c4061.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmfDLFRRc9v9RDxFEWbwh2mB70zogu608',
    appId: '1:1079119056326:ios:19374d8276d2ce1afef6c7',
    messagingSenderId: '1079119056326',
    projectId: 'movie-app-c4061',
    storageBucket: 'movie-app-c4061.appspot.com',
    iosBundleId: 'com.example.movieApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFdoLcbMudJ5SkTwhxJmSQmyV1qkQxa8Y',
    appId: '1:1079119056326:web:9fe07835518d02f1fef6c7',
    messagingSenderId: '1079119056326',
    projectId: 'movie-app-c4061',
    authDomain: 'movie-app-c4061.firebaseapp.com',
    storageBucket: 'movie-app-c4061.appspot.com',
  );
}
